linters:
  enable:
    # https://github.com/golangci/golangci-lint#enabled-by-default-linters
    # Additional linters you want to activate may be specified here...

    # ---
    # https://github.com/mgechev/revive
    # # replacement for the now deprecated official golint linter, see https://github.com/golang/go/issues/38968
    - revive
    
    # ---
    # https://github.com/maratori/testpackage
    # used to enforce blackbox testing
    - testpackage
    
    # ---
    # https://github.com/securego/gosec
    # inspects source code for security problems by scanning the Go AST.
    - gosec

issues:
  exclude-rules:
    # Exclude gosec from running on tests files.
    - path: _test\.go
      linters:
        - gosec
    # Exclude gosec from running in our internal/test pkg
    - path: internal/test
      linters:
        - gosec

linters-settings:
  revive:
    rules:
      # https://github.com/mgechev/revive/blob/master/defaults.toml
      # Previous golint defaults, must be explicit until https://github.com/mgechev/revive/issues/517 lands
      # Also see https://github.com/mgechev/revive#available-rules
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      # - name: exported
      # - name: if-return
      - name: increment-decrement
      # - name: var-naming
      # - name: var-declaration
      # - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf